agent:
  mode: flow
  configMap:
    create: true
    content: |
      logs:
        configs:
        - name: default
          clients:
            - url: http://lgtm-stack-loki.lgtm.svc.cluster.local:3100/loki/api/v1/push
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
            - job_name: pod-logs
              kubernetes_sd_configs:
                - role: pod
              pipeline_stages:
                - docker: {}
      metrics:
        configs:
        - name: default
          remote_write:
            - url: http://lgtm-stack-mimir.lgtm.svc.cluster.local:9009/api/v1/push
          scrape_configs:
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
      traces:
        configs:
        - name: default
          remote_write:
            - endpoint: lgtm-stack-tempo.lgtm.svc.cluster.local:4317
              insecure: true
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
