mode: daemonset
config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  processors:
    batch:
  exporters:
    otlp:
      endpoint: lgtm-stack-mimir.lgtm.svc.cluster.local:9009
      tls:
        insecure: true
    logging:
    loki:
      endpoint: http://lgtm-stack-loki.lgtm.svc.cluster.local:3100/loki/api/v1/push
    jaeger:
      endpoint: lgtm-stack-tempo.lgtm.svc.cluster.local:14250
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp, logging]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [loki, logging]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [jaeger, logging]
